#!/usr/bin/env bash

# prepare the container
if [ ! -d /.composer ]; then
    mkdir /.composer
fi
mkdir /var/log/php-fpm/
chmod -R ugo+rw /.composer

# prepare SSL on the container
chmod +x /opt/scripts/make-localhost-cert
/opt/scripts/make-localhost-cert /var/www/localhost.crt

# prepare the web application
chown -R www-data:www-data /var/www/html
mkdir /var/log/html/cron.d/
chmod o+rwx /var/www/html/cron.d/*.sh

find /var/www/html/ -type f -exec chmod 644 {} \;
find /var/www/html/ -type d -exec chmod 755 {} \;

# start the a container services
/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
