#!/usr/bin/env bash

# prepare the container
if [ ! -d /.composer ]; then
    mkdir /.composer
fi
mkdir /var/log/php-fpm/
chmod -R ugo+rw /.composer

# prepare SSL on the container
chmod +x /opt/scripts/make-localhost-cert
/opt/scripts/make-localhost-cert /var/www/localhost.crt

# Prepare custom nginx files
mkdir -p /var/www/html/nginx.d/
if test -e /var/www/html/nginx.d/php-fpm.conf; then
    cp /var/www/html/nginx.d/php-fpm.conf /etc/php/8.0/fpm/pool.d/www.conf
fi
if test -e /var/www/html/nginx.d/nginx.conf; then
    cp /var/www/html/nginx.d/nginx.conf /etc/nginx/sites-available/default
fi
if test -e /var/www/html/nginx.d/nginx-ssl.conf; then
    cp /var/www/html/nginx.d/nginx-ssl.conf /etc/nginx/sites-enabled/default-ssl
fi
if test -e /var/www/html/nginx.d/php.ini; then
    cp /var/www/html/nginx.d/php.ini /etc/php/8.0/fpm/php.ini
    cp /var/www/html/nginx.d/php.ini /etc/php/8.0/cli/php.ini
fi

# Moving potential supervisor files
if test -d /var/www/html/supervisor.d/; then
    cp -r /var/www/html/supervisor.d/* /etc/supervisor/conf.d/
fi

# Setting web application permissions
chown -R www-data:www-data /var/www/html

find /var/www/html/ -type f ! -path '*.sh' ! -path '/var/www/html/console' -exec chmod 644 {} \;
find /var/www/html/ -type d -exec chmod 755 {} \;

# Prep the cron.d directory
mkdir /var/log/html/cron.d/
chmod o+rwx /var/www/html/cron.d/*.sh
find /var/www/html/cron.d -type f ! -path '*.sh' -delete

# start the a container services
/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf

exit